### ISSUE TITLE
[로또 피드백]

### ISSUE THREAD

**Issue by dayannne** [ChoByungHyun/Web-Training-Collection#8]
- [x] 숫자 3자리마다 쉼표가 표기 되면 좋을 것 같습니다~
- [x] 숫자 목록 스크롤 처리되면 좋을 것 같습니다
- [x] 금액 입력하지 않았을 때에도 결과 확인되는 부분
   <img width="321" alt="image" src="https://github.com/ChoByungHyun/Web-Training-Collection/assets/105140201/fdd9a09f-86d8-46e2-ac2e-466dc05505b3">
- [x] 당첨 번호 2자리수 이상 & 숫자 45 초과하는 숫자 막기 
   <img width="352" alt="image" src="https://github.com/ChoByungHyun/Web-Training-Collection/assets/105140201/70dde857-e458-4e63-a042-ddd3134997dc">

**Comment by ChoByungHyun** [comment]
완료~ 피드백 감사합니다.
숫자 3자리 콤마는 원래 있었슴다!
